server:
  port: 8088

# Spring配置
spring:
  application:
    name: simple-commerce
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
#    default-property-inclusion: non_null
#    mapper:
      # 格式化JSON按照字典顺序排序
#      sort-properties-alphabetically: true
  config:
    use-legacy-processing: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.210.50:3306/simple-commerce?useSSL=false&serverTimezone=UTC
    username: simple-commerce
    password: LnpDE3ACHz8p7EJ8

  redis:
    host: localhost
    password: ""
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s


  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    listener:
      simple:
        #自动签收auto  手动 manual
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    asia.oxox.charon.simplecommerce: debug



# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: 简单电商项目
  application-version: 1.0
  application-description: 测试用的项目
  try-host: http://localhost:${server.port}
