server:
  port: 8088

# Spring配置
spring:
  application:
    name: simple-commerce
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
#    default-property-inclusion: non_null
    mapper:
      # 格式化JSON按照字典顺序排序
      sort-properties-alphabetically: true
  config:
    use-legacy-processing: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.210.50:3306/simple-commerce?useSSL=false&serverTimezone=UTC
    username: simple-commerce
    password: LnpDE3ACHz8p7EJ8
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
  type-aliases-package: com.hmdp.entity # ?????
logging:
  level:
    com.hmdp: debug



# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: 简单电商项目
  application-version: 1.0
  application-description: 测试用的项目
  try-host: http://localhost:${server.port}