---
--- Generated by Luanalysis
--- Created by charon.
--- DateTime: 2023/4/30 10:35
---

-- 加载Java类和库文件
local BigDecimal = require("java.math.BigDecimal")
local CoerceJavaToLua = require("org.luaj.vm2.lib.jse.CoerceJavaToLua")

-- 定义两个浮点数
local num1 = BigDecimal.new("1.23")
local num2 = BigDecimal.new("4.56")

-- 进行加法计算
local result = num1:add(num2)

-- 输出结果
return result